#!/bin/sh

if [ x$1 != xgen ] ; then
	echo "Tcite project file generator:"
	echo
	echo "  Must be called in project root folder. Will create prj/<name>.tct."
	echo "  If no name given, take the current folder name."
	echo
	echo "  Usage: $0 gen [prj_name]"
	echo
	exit 1
fi

if [ x$2 == x ] ; then
	prj_name=$(basename $(pwd))
else
	prj_name=$2
fi

if [ -d prj ] ; then
	echo "Folder 'prj' already existing"
	exit 1
fi

mkdir prj
prj_file=prj/$prj_name.tct

touch $prj_file

echo "# File generated by $0" >> $prj_file
echo >> $prj_file
echo "proj.name=$prj_name" >> $prj_file
echo "proj.path=.."  >> $prj_file
echo >> $prj_file

base=$(pwd)
for d in $(find * -type d); do
	ext="c c++ cc cp cpp cxx h h++ hh hp hpp hxx C H py"
	match=""
	for e in $ext; do
		if ls $d/*.$e 1> /dev/null 2>&1; then
			match="$d/*.$e; $match"
		fi
 	done

	[ -n "$match" ] && echo "proj.include.++= $d | $match"  >> $prj_file
done


