# The construction file for SinkWorld C++ Lexers
import os
import glob
src = "."
sources = [os.path.basename(x) for x in glob.glob(src + os.sep + "*.cxx")]
env = Environment(CPPPATH=["../base"],CXXFLAGS = ["-nologo", "-EHsc", "-MD", "-Zi"])
# Needed because installing VC 2005 confuses scons discovery of VC
for v in ['PATH', 'INCLUDE']:
	env['ENV'][v] = os.environ[v]
env.StaticLibrary("lexers", sources)
